import { createContext, useContext, useState, useEffect } from 'react';
import { initialAllUsers } from '../data/mockData';
import { supabase } from '../config/supabase';

const AdminContext = createContext(null);

let nextCompanyId = 100;
let nextUserId = 100;

export function AdminProvider({ children, currentUser }) {
    // DB table: companies(id, name, logo_url, status, created_at)
    const [companies, setCompanies] = useState([]);
    const [loadingCompanies, setLoadingCompanies] = useState(true);

    useEffect(() => {
        if (currentUser?.role === 'super_admin') {
            fetchCompanies();
        } else {
            setLoadingCompanies(false);
        }
    }, [currentUser]);

    const fetchCompanies = async () => {
        setLoadingCompanies(true);
        const { data, error } = await supabase
            .from('companies')
            .select('*')
            .order('created_at', { ascending: false });

        if (!error && data) {
            const mapped = data.map(c => ({
                id: c.id,
                name: c.name,
                logoUrl: c.logo_url,
                status: c.status,
                createdAt: new Date(c.created_at).toLocaleDateString('es-AR', { day: '2-digit', month: '2-digit', year: '2-digit' }),
                rawTs: new Date(c.created_at).getTime()
            }));
            setCompanies(mapped);
        }
        setLoadingCompanies(false);
    };

    // DB table: profiles(id, email, name, role, company_id, status, ...)
    const [allUsers, setAllUsers] = useState(initialAllUsers);

    // ─── Company Actions ─────────────────────────────────────────────────────
    // DB: INSERT INTO companies(name, logo_url, status) VALUES (...)
    const addCompany = ({ name, logoUrl = null, status = 'Activo' }) => {
        const now = new Date();
        const dateStr = now.toLocaleDateString('es-AR', { day: '2-digit', month: '2-digit', year: '2-digit' });
        const newCompany = {
            id: `company-${nextCompanyId++}`,   // DB: uuid generated by DB
            name,                               // DB: companies.name
            logoUrl,                            // DB: companies.logo_url (storage URL)
            status,                             // DB: companies.status
            createdAt: dateStr,                 // DB: companies.created_at (formatted)
            rawTs: Date.now(),                  // DB: companies.created_at (unix ms)
        };
        setCompanies(prev => [newCompany, ...prev]);
        return newCompany;
    };

    // DB: UPDATE companies SET status = ? WHERE id = ?
    const toggleCompanyStatus = (companyId) => {
        setCompanies(prev => prev.map(c =>
            c.id === companyId
                ? { ...c, status: c.status === 'Activo' ? 'Inactivo' : 'Activo' }
                : c
        ));
    };

    // DB: UPDATE companies SET name = ?, logo_url = ? WHERE id = ?
    const updateCompany = (companyId, updates) => {
        setCompanies(prev => prev.map(c =>
            c.id === companyId ? { ...c, ...updates } : c
        ));
    };

    // ─── User Actions ────────────────────────────────────────────────────────
    // DB: INSERT INTO auth.users + INSERT INTO profiles(...)
    const addUser = ({ email, name, role, companyId, companyName, password, avatarUrl = null }) => {
        const initials = name.split(' ').map(w => w[0]).join('').slice(0, 2).toUpperCase();
        const newUser = {
            id: `user-${nextUserId++}`,         // DB: auth.users.id (uuid)
            email,                              // DB: auth.users.email
            name,                              // DB: profiles.name
            role,                              // DB: profiles.role ENUM(...)
            companyId,                         // DB: profiles.company_id
            companyName,                       // DB: companies.name (joined)
            status: 'Activo',                  // DB: profiles.status
            initials,                          // DB: derived or stored
            avatarUrl,                         // DB: profiles.avatar_url (Storage URL)
            agentId: role !== 'client' ? `agent-${nextUserId}` : null, // DB: profiles.agent_id
            clientId: role === 'client' ? `client-${nextUserId}` : null, // DB: profiles.client_id
            // password is shown once; DB: bcrypt-hashed in auth.users
            _tempPassword: password,
        };
        setAllUsers(prev => [newUser, ...prev]);
        return newUser;
    };


    // DB: UPDATE profiles SET status = ? WHERE id = ?
    const toggleUserStatus = (userId) => {
        setAllUsers(prev => prev.map(u =>
            u.id === userId
                ? { ...u, status: u.status === 'Activo' ? 'Inactivo' : 'Activo' }
                : u
        ));
    };

    // ─── Derived helpers ─────────────────────────────────────────────────────
    // Users belonging to a specific company (for admin_empresa Settings view)
    const getUsersByCompany = (companyId) =>
        allUsers.filter(u => u.companyId === companyId);

    const getAgentsByCompany = (companyId) =>
        allUsers.filter(u => u.companyId === companyId && u.role !== 'client');

    const getClientsByCompany = (companyId) =>
        allUsers.filter(u => u.companyId === companyId && u.role === 'client');

    // User count per company (for super_admin table)
    const getUserCountByCompany = (companyId) =>
        allUsers.filter(u => u.companyId === companyId).length;

    return (
        <AdminContext.Provider value={{
            companies,
            loadingCompanies,
            allUsers,
            currentUser,                    // DB: auth.users + profiles
            addCompany,
            toggleCompanyStatus,
            updateCompany,
            addUser,
            toggleUserStatus,
            getUsersByCompany,
            getAgentsByCompany,
            getClientsByCompany,
            getUserCountByCompany,
            fetchCompanies,
        }}>
            {children}
        </AdminContext.Provider>
    );
}

export function useAdmin() {
    const ctx = useContext(AdminContext);
    if (!ctx) throw new Error('useAdmin must be used within AdminProvider');
    return ctx;
}
